# Generated by Django 5.0 on 2023-12-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_image', models.ImageField(upload_to='about/')),
                ('section1_header', models.CharField(max_length=50)),
                ('section1_text', models.TextField()),
                ('section2_image', models.ImageField(upload_to='about/')),
                ('section2_header', models.CharField(max_length=50)),
                ('section2_text', models.TextField()),
                ('card1_image', models.ImageField(upload_to='about/')),
                ('card1_header', models.CharField(max_length=50)),
                ('card1_text', models.CharField(max_length=150)),
                ('card2_image', models.ImageField(upload_to='about/')),
                ('card2_header', models.CharField(max_length=50)),
                ('card2_text', models.CharField(max_length=150)),
                ('card3_image', models.ImageField(upload_to='about/')),
                ('card3_header', models.CharField(max_length=50)),
                ('card3_text', models.CharField(max_length=150)),
                ('bottom_section_header', models.CharField(max_length=50)),
                ('bottom_section_text', models.TextField()),
            ],
        ),
    ]
