# Generated by Django 5.0 on 2023-12-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='bottom_section_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='card1_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='bottom_section_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card1_header',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card1_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card2_header',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card2_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card2_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card3_header',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card3_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='card3_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section1_header',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section1_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section1_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section2_header',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section2_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section2_text',
        ),
    ]
