# Generated by Django 5.0 on 2023-12-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_bottom_section_header_about_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='header',
            new_name='bottom_section_header',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='bottom_section_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='card1_header',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='card1_image',
            field=models.ImageField(default=None, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='card1_text',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='card2_header',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='card2_image',
            field=models.ImageField(default=None, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='card2_text',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='card3_header',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='card3_image',
            field=models.ImageField(default=None, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='card3_text',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='section1_header',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='section1_image',
            field=models.ImageField(default=None, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='section1_text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='about',
            name='section2_header',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='section2_image',
            field=models.ImageField(default=None, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='section2_text',
            field=models.TextField(default=None),
        ),
    ]
